# pull official base image
FROM python:3.10.8-slim-buster

# create directory for the app user
# use array form because buildx has a bug it seems: https://github.com/moby/buildkit/issues/2437
RUN ["mkdir", "-p", "/home/app"]

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN ["apt-get", "update"]
RUN ["apt-get", "-y", "install", "netcat gcc postgresql"]
RUN ["apt-get", "clean"]

# install python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "uvicorn[standard]==0.19.0"

# add app
COPY . .

# run as non-root user
RUN ["useradd", "-m", "myuser"]
USER myuser

# run gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker